/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThucHanh2;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giang Vu
 */
public class formDanhSachThiSinh extends javax.swing.JFrame {

    /**
     * Creates new form formDanhSachSinhVien
     */
    public formDanhSachThiSinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radTatCa = new javax.swing.JRadioButton();
        radTop5DiemCaoNhat = new javax.swing.JRadioButton();
        radDatDiemSan = new javax.swing.JRadioButton();
        radCoDiemLiet = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThiSinh = new javax.swing.JTable();
        btnThemMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Du lieu tuyen sinh tu file"));

        jLabel1.setText("Ten file:");

        jButton1.setText("Chon file");

        jLabel2.setText("Danh sach thi sinh:");

        buttonGroup1.add(radTatCa);
        radTatCa.setText("Tat ca");
        radTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTatCaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radTop5DiemCaoNhat);
        radTop5DiemCaoNhat.setText("Top 5 diem cao nhat");
        radTop5DiemCaoNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTop5DiemCaoNhatActionPerformed(evt);
            }
        });

        buttonGroup1.add(radDatDiemSan);
        radDatDiemSan.setText("Dat diem san");
        radDatDiemSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDatDiemSanActionPerformed(evt);
            }
        });

        buttonGroup1.add(radCoDiemLiet);
        radCoDiemLiet.setText("Co diem liet");
        radCoDiemLiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCoDiemLietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(radTatCa)
                .addGap(18, 18, 18)
                .addComponent(radTop5DiemCaoNhat)
                .addGap(18, 18, 18)
                .addComponent(radDatDiemSan)
                .addGap(18, 18, 18)
                .addComponent(radCoDiemLiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(radTatCa)
                    .addComponent(radTop5DiemCaoNhat)
                    .addComponent(radDatDiemSan)
                    .addComponent(radCoDiemLiet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sach thi sinh"));

        tblThiSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblThiSinh);

        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ThucHanh2/Images/them.png"))); // NOI18N
        btnThemMoi.setText("Them moi");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ThucHanh2/Images/sua.gif"))); // NOI18N
        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ThucHanh2/Images/xoa.gif"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ThucHanh2/Images/dong.png"))); // NOI18N
        btnDong.setText("Dong");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThemMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnDong)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThemMoi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        // Khai bao 1 doi tuong form
        formThemThiSinh formThem = new formThemThiSinh();
        formThem.setVisible(true);
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Goi ham hien thi danh sach
        hienThiDanhSachThiSinh();
        radTatCa.setSelected(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String soBaoDanh = "";
        
        // Lay thong tin ma sinh vien nguoi dung chon tren table
        int dongChon = tblThiSinh.getSelectedRow();
        soBaoDanh = "" + tblThiSinh.getValueAt(dongChon, 0);
        formThemThiSinh formSua = new formThemThiSinh();
        
        // Truyen ma sinh vien len form sua
        formSua.setSoBaoDanh(soBaoDanh);
        
        formSua.setVisible(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int ketQua = JOptionPane.showConfirmDialog(rootPane,
                "Ban co chac chan muon xoa thi sinh nay khong?",
                "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        
        if (ketQua == JOptionPane.YES_OPTION)
        {
            // Xu ly xoa
            String soBaoDanh = "";
            
            // Lay thong tin ma sinh vien nguoi dung chon tren table
            int dongChon = tblThiSinh.getSelectedRow();
            soBaoDanh = "" + tblThiSinh.getValueAt(dongChon, 0);

            boolean ketQuaXoa = DataProvider.QLThiSinh().xoaThiSinh(soBaoDanh);
            if (ketQuaXoa == true) {
                JOptionPane.showMessageDialog(rootPane, "Xoa thong tin sinh vien thanh cong");
            }
        }
        formDanhSachThiSinh.hienThiDanhSachThiSinh();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void radTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTatCaActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachThiSinh();
    }//GEN-LAST:event_radTatCaActionPerformed

    private void radTop5DiemCaoNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTop5DiemCaoNhatActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachThiSinh(DataProvider.QLThiSinh().danhSachTop5DiemCaoNhat());
    }//GEN-LAST:event_radTop5DiemCaoNhatActionPerformed

    private void radDatDiemSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDatDiemSanActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachThiSinh(DataProvider.QLThiSinh().danhSachDatDiemSan());
    }//GEN-LAST:event_radDatDiemSanActionPerformed

    private void radCoDiemLietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCoDiemLietActionPerformed
        // TODO add your handling code here:
        hienThiDanhSachThiSinh(DataProvider.QLThiSinh().danhSachCoDiemLiet());
    }//GEN-LAST:event_radCoDiemLietActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        // Dong ung dung
        int ketQua = JOptionPane.showConfirmDialog(rootPane,
                "Ban co chac chan muon dong chuong trinh khong?",
                "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (ketQua == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnDongActionPerformed
    
    public static void hienThiDanhSachThiSinh()
    {
        // Khai bao 1 mang chua tieu de
        String tieuDe[] = new String[]{"Ma SV", "Ho ten", "Gioi tinh", "Ngay sinh", "Dia chi", "Tong diem", "Diem Toan", "Diem Ly", "Diem Hoa"};
        
        // Khai bao 1 doi tuong de dua du lieu len table
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        
        // Lay danh sach
        List<ThiSinh> lstSV = DataProvider.QLThiSinh().layDanhSachThiSinh();
        
        // Duyet danh sach de dua vao model
        Object row[];
        for (ThiSinh ts : lstSV)
        {
            row = new Object[9];
            row[0] = ts.getSoBaoDanh();
            row[1] = ts.getHoTen();
            row[2] = ts.getGioiTinh();
            row[3] = ts.getNgaySinh();
            row[4] = ts.getDiaChi();
            row[5] = ts.getTongDiem();
            row[6] = ts.getDiemToan();
            row[7] = ts.getDiemLy();
            row[8] = ts.getDiemHoa();
            
            // Them vao model
            model.addRow(row);
        }
        
        // Hien thi du lieu len table
        tblThiSinh.setModel(model);
    }
    
    public static void hienThiDanhSachThiSinh(List<ThiSinh> lstSV)
    {
        // Khai bao 1 mang chua tieu de
        String tieuDe[] = new String[]{"Ma SV", "Ho ten", "Gioi tinh", "Ngay sinh", "Dia chi", "Tong diem", "Diem Toan", "Diem Ly", "Diem Hoa"};
        
        // Khai bao 1 doi tuong de dua du lieu len table
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        
        // Duyet danh sach de dua vao model
        Object row[];
        for (ThiSinh ts : lstSV)
        {
            row = new Object[9];
            row[0] = ts.getSoBaoDanh();
            row[1] = ts.getHoTen();
            row[2] = ts.getGioiTinh();
            row[3] = ts.getNgaySinh();
            row[4] = ts.getDiaChi();
            row[5] = ts.getTongDiem();
            row[6] = ts.getDiemToan();
            row[7] = ts.getDiemLy();
            row[8] = ts.getDiemHoa();
            
            // Them vao model
            model.addRow(row);
        }
        
        // Hien thi du lieu len table
        tblThiSinh.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDanhSachThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDanhSachThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDanhSachThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDanhSachThiSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDanhSachThiSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radCoDiemLiet;
    private javax.swing.JRadioButton radDatDiemSan;
    private javax.swing.JRadioButton radTatCa;
    private javax.swing.JRadioButton radTop5DiemCaoNhat;
    private static javax.swing.JTable tblThiSinh;
    // End of variables declaration//GEN-END:variables
}
