/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThucHanh;

import javax.swing.JOptionPane;

/**
 *
 * @author Truong Giang
 */
public class formTinhTongChuoiSo extends javax.swing.JFrame {

    /**
     * Creates new form formTinhTongChuoiSo
     */
    public formTinhTongChuoiSo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChuoiSo2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChuoiSo1 = new javax.swing.JTextArea();
        btnTinhTong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTongChuoi1 = new javax.swing.JLabel();
        lblTongChuoi2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tinh Tong Chuoi So");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tinh tong chuoi so"));

        jLabel1.setText("Nhap vao chuoi so 1:");

        jLabel2.setText("Nhap vao chuoi so 2:");

        txtChuoiSo2.setColumns(20);
        txtChuoiSo2.setRows(5);
        jScrollPane1.setViewportView(txtChuoiSo2);

        txtChuoiSo1.setColumns(20);
        txtChuoiSo1.setRows(5);
        jScrollPane2.setViewportView(txtChuoiSo1);

        btnTinhTong.setText("Tinh tong");
        btnTinhTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTongActionPerformed(evt);
            }
        });

        jLabel3.setText("Tong chuoi so 1:");

        jLabel4.setText("Tong chuoi so 2:");

        lblTongChuoi1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongChuoi1.setText("none");

        lblTongChuoi2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongChuoi2.setText("none");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTinhTong))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTongChuoi1)
                                    .addComponent(lblTongChuoi2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTinhTong)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTongChuoi1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTongChuoi2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTongActionPerformed
        // TODO add your handling code here:
        String strChuoiSo1 = "", strChuoiSo2 = "", strTongChuoi1 = "", strTongChuoi2 = "";
        
        strChuoiSo1 = txtChuoiSo1.getText();
        strChuoiSo2 = txtChuoiSo2.getText();
        
        String a1[] = strChuoiSo1.split(",");
        String a2[] = strChuoiSo2.split(",");
        
        int chuoiSo1[] = new int[a1.length];
        int chuoiSo2[] = new int[a2.length];
        
        int tongChuoi1 = 0, tongChuoi2 = 0;
        
        if (strChuoiSo1.length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap vao day so");
            txtChuoiSo1.requestFocus();
            return;
        }
        
        if (strChuoiSo2.length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap vao day so");
            txtChuoiSo2.requestFocus();
            return;
        }
        
        try {
            // Chuyen chuoi string sang chuoi int
            for (int i = 0; i < a1.length; i++)
            {
                chuoiSo1[i] = Integer.parseInt(a1[i]);
                tongChuoi1 += chuoiSo1[i];
            }
            for (int i = 0; i < a2.length; i++)
            {
                chuoiSo2[i] = Integer.parseInt(a2[i]);
                tongChuoi2 += chuoiSo2[i];
            }
            strTongChuoi1 = Integer.toString(tongChuoi1);
            strTongChuoi2 = Integer.toString(tongChuoi2);
            
            lblTongChuoi1.setText(strTongChuoi1);
            lblTongChuoi2.setText(strTongChuoi2);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap gia tri kieu so. Chi tiet loi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTinhTongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblTongChuoi1.setText("");
        lblTongChuoi2.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTinhTongChuoiSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTinhTongChuoiSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTinhTongChuoiSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTinhTongChuoiSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTinhTongChuoiSo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhTong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTongChuoi1;
    private javax.swing.JLabel lblTongChuoi2;
    private javax.swing.JTextArea txtChuoiSo1;
    private javax.swing.JTextArea txtChuoiSo2;
    // End of variables declaration//GEN-END:variables
}
