/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThucHanh;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Truong Giang
 */
public class formNhapVaSapXep extends javax.swing.JFrame {

    /**
     * Creates new form formNhapVaSapXep
     */
    public formNhapVaSapXep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDaySo = new javax.swing.JTextField();
        btnSapXep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKetQua = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDanhSachSoLe = new javax.swing.JLabel();
        lblTongSoLe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSoLuongSo5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTop3GiaTri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhap Va Sap Xep Day So");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhap va sap xep day so"));

        jLabel1.setText("Nhap vao day so:");

        btnSapXep.setText("Sap xep");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListKetQua);

        jLabel2.setText("Ket qua:");

        jLabel3.setText("Danh sach cac so le:");

        jLabel4.setText("Tong cac so le:");

        lblDanhSachSoLe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDanhSachSoLe.setText("none");

        lblTongSoLe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTongSoLe.setText("none");

        jLabel5.setText("So luong so 5 xuat hien:");

        lblSoLuongSo5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSoLuongSo5.setText("none");

        jLabel6.setText("Top 3 gia tri cao nhat:");

        lblTop3GiaTri.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTop3GiaTri.setText("none");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSapXep))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDaySo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDanhSachSoLe)
                                    .addComponent(lblTongSoLe)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTop3GiaTri)
                                    .addComponent(lblSoLuongSo5))))
                        .addGap(0, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDaySo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSapXep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDanhSachSoLe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTongSoLe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSoLuongSo5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTop3GiaTri))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
        String strDaySo = "";
        
        strDaySo = txtDaySo.getText();
        
        String a[] = strDaySo.split(",");
        
        int daySo[] = new int[a.length];
        
        if (strDaySo.length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap vao day so");
            txtDaySo.requestFocus();
            return;
        }
        
        try {
            // Chuyen chuoi string sang chuoi int
            for (int i = 0; i < a.length; i++)
            {
                daySo[i] = Integer.parseInt(a[i]);
            }
            int temp = 0;

            for (int i = 0; i < daySo.length - 1; i++)
            {
                for (int j = i + 1; j < daySo.length; j++)
                {
                    if (daySo[i] > daySo[j])
                    {
                        temp = daySo[i];
                        daySo[i] = daySo[j];
                        daySo[j] = temp;
                    }
                }
            }
        
            DefaultListModel model = new DefaultListModel();

            for (int i = 0; i < daySo.length; i++)
            {
                model.addElement(daySo[i]);
            }

            // Hien thi vao jList
            jListKetQua.setModel(model);
            
            // Tim va tinh tong cac so le
            String strDanhSachSoLe = "", strTongSoLe = "";
            int tongSoLe = 0;
            
            for (int i = 0; i < daySo.length; i++)
            {
                if (daySo[i] % 2 != 0)
                {
                    strDanhSachSoLe += daySo[i] + ", ";
                    tongSoLe += daySo[i];
                }
            }
            // Xoa dau , o cuoi danh sach
            strDanhSachSoLe = strDanhSachSoLe.substring(0, strDanhSachSoLe.length() - 2);
            
            strTongSoLe = Integer.toString(tongSoLe);
            
            lblDanhSachSoLe.setText(strDanhSachSoLe);
            lblTongSoLe.setText(strTongSoLe);
            
            // Thong ke so luong so 5 xuat hien
            int count = 0;
            String strCount = "";
            for(int i = 0; i < strDaySo.length(); i++)
            {    
                if(strDaySo.charAt(i) == '5')
                count++;
            }
            strCount = Integer.toString(count);
            lblSoLuongSo5.setText(strCount + " lan");
            
            // Top 3 gia tri cao nhat
            String strTop3GiaTri = "" + daySo[daySo.length - 1] + ", " + daySo[daySo.length - 2] + ", " + daySo[daySo.length - 3];
            lblTop3GiaTri.setText(strTop3GiaTri);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap gia tri kieu so. Chi tiet loi: " + e.getMessage());
            txtDaySo.requestFocus();
            return;
        }
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblDanhSachSoLe.setText("");
        lblTongSoLe.setText("");
        lblSoLuongSo5.setText("");
        lblTop3GiaTri.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formNhapVaSapXep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formNhapVaSapXep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formNhapVaSapXep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formNhapVaSapXep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formNhapVaSapXep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSapXep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListKetQua;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDanhSachSoLe;
    private javax.swing.JLabel lblSoLuongSo5;
    private javax.swing.JLabel lblTongSoLe;
    private javax.swing.JLabel lblTop3GiaTri;
    private javax.swing.JTextField txtDaySo;
    // End of variables declaration//GEN-END:variables
}
