/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package part3ClassVaObject.ChuongTrinhTinhToan;

import javax.swing.JOptionPane;

/**
 *
 * @author Giang Vu
 */
public class formTinhToan extends javax.swing.JFrame {

    /**
     * Creates new form formTinhToan
     */
    public formTinhToan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblGiaiThua = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtChieuCao = new javax.swing.JTextField();
        txtDayBe = new javax.swing.JTextField();
        txtDayLon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblDienTichHinhThang = new javax.swing.JLabel();
        btnTinhToanHinhThang = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtBanKinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDienTichHinhTron = new javax.swing.JLabel();
        lblChuViHinhTron = new javax.swing.JLabel();
        btnTinhToanHinhTron = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtChieuDai = new javax.swing.JTextField();
        txtChieuRong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTinhToanHinhChuNhat = new javax.swing.JButton();
        lblChuViHinhChuNhat = new javax.swing.JLabel();
        lblDienTichHinhChuNhat = new javax.swing.JLabel();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chuong Trinh Tinh Toan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setText("So tu nhien n:");

        jLabel14.setText("Giai thua:");

        lblGiaiThua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGiaiThua.setText("none");

        jButton1.setText("Tinh Toan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGiaiThua)
                                .addGap(0, 313, Short.MAX_VALUE))
                            .addComponent(txtN)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblGiaiThua))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Giai Thua", jPanel1);

        jLabel8.setText("Day lon:");

        jLabel9.setText("Day be:");

        jLabel10.setText("Chieu cao:");

        jLabel11.setText("Dien tich:");

        lblDienTichHinhThang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDienTichHinhThang.setText("none");

        btnTinhToanHinhThang.setText("Tinh Toan");
        btnTinhToanHinhThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhToanHinhThangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDienTichHinhThang)
                                .addGap(0, 335, Short.MAX_VALUE))
                            .addComponent(txtChieuCao)
                            .addComponent(txtDayBe)
                            .addComponent(txtDayLon)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTinhToanHinhThang)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDayLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDayBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtChieuCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDienTichHinhThang))
                .addGap(18, 18, 18)
                .addComponent(btnTinhToanHinhThang)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hinh Thang", jPanel2);

        jLabel5.setText("Ban kinh:");

        jLabel6.setText("Chu vi:");

        jLabel7.setText("Dien tich:");

        lblDienTichHinhTron.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDienTichHinhTron.setText("none");

        lblChuViHinhTron.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblChuViHinhTron.setText("none");

        btnTinhToanHinhTron.setText("Tinh Toan");
        btnTinhToanHinhTron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhToanHinhTronActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTinhToanHinhTron))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBanKinh, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDienTichHinhTron)
                                    .addComponent(lblChuViHinhTron))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBanKinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblChuViHinhTron))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDienTichHinhTron)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnTinhToanHinhTron)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hinh Tron", jPanel3);

        jLabel1.setText("Chieu dai:");

        jLabel2.setText("Chieu rong:");

        jLabel3.setText("Chu vi:");

        jLabel4.setText("Dien tich:");

        btnTinhToanHinhChuNhat.setText("Tinh Toan");
        btnTinhToanHinhChuNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhToanHinhChuNhatActionPerformed(evt);
            }
        });

        lblChuViHinhChuNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblChuViHinhChuNhat.setText("none");

        lblDienTichHinhChuNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDienTichHinhChuNhat.setText("none");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtChieuDai))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChieuRong, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChuViHinhChuNhat)
                                    .addComponent(lblDienTichHinhChuNhat))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTinhToanHinhChuNhat)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChieuDai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChieuRong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblChuViHinhChuNhat))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDienTichHinhChuNhat))
                .addGap(18, 18, 18)
                .addComponent(btnTinhToanHinhChuNhat)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hinh Chu Nhat", jPanel4);

        btnDong.setText("Dong");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDong)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDong)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhToanHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhToanHinhChuNhatActionPerformed
        // TODO add your handling code here:
        String strChieuDai = "", strChieuRong = "", strChuVi = "", strDienTich = "";
        double chieuDai = 0, chieuRong = 0;
        
        strChieuDai = txtChieuDai.getText();
        strChieuRong = txtChieuRong.getText();
        
        try
        {
            if (strChieuDai.length() == 0 || strChieuDai.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri chieu dai");
                txtChieuDai.requestFocus();
                return;
            }
            
            if (strChieuRong.length() == 0 || strChieuRong.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri chieu rong");
                txtChieuRong.requestFocus();
                return;
            }
            
            chieuDai = Double.parseDouble(strChieuDai);
            chieuRong = Double.parseDouble(strChieuRong);

            TinhToan tt = new TinhToan();

            strChuVi = tt.chuViHinhChuNhat(chieuDai, chieuRong) + "";
            strDienTich = tt.dienTichHinhChuNhat(chieuDai, chieuRong) + "";

            lblChuViHinhChuNhat.setText(strChuVi);
            lblDienTichHinhChuNhat.setText(strDienTich);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap gia tri kieu so. Chi tiet loi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTinhToanHinhChuNhatActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        int ketQua = JOptionPane.showConfirmDialog(rootPane,
                "Ban co chac chan muon dong chuong trinh khong?",
                "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (ketQua == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnTinhToanHinhTronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhToanHinhTronActionPerformed
        // TODO add your handling code here:
        String strBanKinh = "", strChuVi = "", strDienTich = "";
        double banKinh = 0;
        
        strBanKinh = txtBanKinh.getText();
        
        try
        {
            if (strBanKinh.length() == 0 || strBanKinh.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri ban kinh");
                txtBanKinh.requestFocus();
                return;
            }
            
            banKinh = Double.parseDouble(strBanKinh);

            TinhToan tt = new TinhToan();

            strChuVi = tt.chuViHinhTron(banKinh);
            strDienTich = tt.dienTichHinhTron(banKinh);

            lblChuViHinhTron.setText(strChuVi);
            lblDienTichHinhTron.setText(strDienTich);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap gia tri kieu so. Chi tiet loi: " + e.getMessage());
            txtBanKinh.requestFocus();
        }
    }//GEN-LAST:event_btnTinhToanHinhTronActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblChuViHinhChuNhat.setText(null);
        lblDienTichHinhChuNhat.setText(null);
        lblChuViHinhTron.setText(null);
        lblDienTichHinhTron.setText(null);
        lblDienTichHinhThang.setText(null);
        lblGiaiThua.setText(null);
    }//GEN-LAST:event_formWindowOpened

    private void btnTinhToanHinhThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhToanHinhThangActionPerformed
        // TODO add your handling code here:
        String strDayLon = "", strDayBe = "", strChieuCao = "", strDienTich = "";
        double dayLon = 0, dayBe = 0, chieuCao = 0;
        
        strDayLon = txtDayLon.getText();
        strDayBe = txtDayBe.getText();
        strChieuCao = txtChieuCao.getText();
        
        try
        {
            if (strDayLon.length() == 0 || strDayLon.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri day lon hop le");
                txtDayLon.requestFocus();
                return;
            }
            
            if (strDayBe.length() == 0 || strDayBe.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri day be hop le");
                txtDayBe.requestFocus();
                return;
            }
            
            if (strChieuCao.length() == 0 || strChieuCao.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri chieu cao hop le");
                txtChieuCao.requestFocus();
                return;
            }

            dayLon = Double.parseDouble(strDayLon);
            dayBe = Double.parseDouble(strDayBe);
            
            if (dayLon < dayBe)
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao day lon lon hon day be");
                txtDayLon.requestFocus();
                return;
            }
            
            chieuCao = Double.parseDouble(strChieuCao);

            TinhToan tt = new TinhToan();

            strDienTich = tt.dienTichHinhThang(dayLon, dayBe, chieuCao);

            lblDienTichHinhThang.setText(strDienTich);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap gia tri kieu so. Chi tiet loi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTinhToanHinhThangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String strN = "", strGiaiThua = "";
        int n = 0;
        
        strN = txtN.getText();
        
        try
        {
            if (strN.length() == 0 || strN.contains("-"))
            {
                JOptionPane.showMessageDialog(rootPane, "Ban phai nhap vao gia tri so tu nhien lon hon hoac bang 0");
                txtN.requestFocus();
                return;
            }
            
            n = Integer.parseInt(strN);
            
            TinhToan tt = new TinhToan();

            strGiaiThua = tt.tinhGiaiThua(n) + "";

            lblGiaiThua.setText(strGiaiThua);
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Ban can phai nhap gia tri kieu so nguyen. Chi tiet loi: " + e.getMessage());
            txtN.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTinhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTinhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTinhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTinhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTinhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnTinhToanHinhChuNhat;
    private javax.swing.JButton btnTinhToanHinhThang;
    private javax.swing.JButton btnTinhToanHinhTron;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChuViHinhChuNhat;
    private javax.swing.JLabel lblChuViHinhTron;
    private javax.swing.JLabel lblDienTichHinhChuNhat;
    private javax.swing.JLabel lblDienTichHinhThang;
    private javax.swing.JLabel lblDienTichHinhTron;
    private javax.swing.JLabel lblGiaiThua;
    private javax.swing.JTextField txtBanKinh;
    private javax.swing.JTextField txtChieuCao;
    private javax.swing.JTextField txtChieuDai;
    private javax.swing.JTextField txtChieuRong;
    private javax.swing.JTextField txtDayBe;
    private javax.swing.JTextField txtDayLon;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
