/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package part6LamViecVoiJDBC;

import part1CauTrucLapTrinh.*;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;

/**
 *
 * @author Truong Giang
 */
public class formDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form formDangNhap
     */
    public formDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDong = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dang Nhap");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhap thong tin dang nhap"));

        jLabel1.setText("Ten dang nhap:");

        jLabel2.setText("Mat khau:");

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/dong.png"))); // NOI18N
        btnDong.setText("Dong");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/dangNhap.gif"))); // NOI18N
        btnDangNhap.setText("Dang nhap");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDangNhap)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnDong)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnDong))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(409, 237));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        // Khai bao bien
        String tenDangNhap = "", matKhau = "";

        // Lay thong tin tu giao dien
        tenDangNhap = txtTenDangNhap.getText();
        matKhau = new String(txtMatKhau.getPassword());
        QuanLyNguoiDung quanLyNguoiDung = new QuanLyNguoiDung();

        NguoiDung objND = quanLyNguoiDung.layThongTinNguoiDung(tenDangNhap);

        if (objND != null) {
            String matKhauMD5 = quanLyNguoiDung.maHoaMD5(matKhau);
            String matKhauBDMD5 = objND.getMatKhau();
            if (matKhauMD5.equals(matKhauBDMD5)) {
                this.setVisible(false);
                formCuaSoChinh formCSC = new formCuaSoChinh();
                // Luu thong tin vao cua so chinh
                formCSC.trangThaiDangNhap = true;
                formCSC.setUserID(objND.getUserID());
                formCSC.setTenDangNhap(tenDangNhap);
                formCSC.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Dang nhap that bai. Ban vui long kiem tra lai mat khau");
                txtMatKhau.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tai khoan khong ton tai. Ban vui long kiem tra lai thong tin");
            // Di chuyen con chuot vao textfield
            txtTenDangNhap.requestFocus();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        // Dong ung dung
        int ketQua = JOptionPane.showConfirmDialog(rootPane,
                "Ban co chac chan muon dong chuong trinh khong?",
                "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (ketQua == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnDongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Xu ly phim Enter khi nhap vao phan Mat khau
        ActionListener l = ae -> {
            // Khai bao bien
            String tenDangNhap = "", matKhau = "";

            // Lay thong tin tu giao dien
            tenDangNhap = txtTenDangNhap.getText();
            matKhau = new String(txtMatKhau.getPassword());
            QuanLyNguoiDung quanLyNguoiDung = new QuanLyNguoiDung();

            NguoiDung objND = quanLyNguoiDung.layThongTinNguoiDung(tenDangNhap);

            if (objND != null) {
                // Ma hoa mat khau
                String matKhauMD5 = quanLyNguoiDung.maHoaMD5(matKhau);
                if (matKhauMD5.equals(objND.getMatKhau())) {
                    this.setVisible(false);
                    formCuaSoChinh formCSC = new formCuaSoChinh();
                    // Luu thong tin vao cua so chinh
                    formCSC.trangThaiDangNhap = true;
                    formCSC.setUserID(objND.getUserID());
                    formCSC.setTenDangNhap(tenDangNhap);
                    formCSC.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Dang nhap that bai. Ban vui long kiem tra lai mat khau");
                    txtMatKhau.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Tai khoan khong ton tai. Ban vui long kiem tra lai thong tin");
                // Di chuyen con chuot vao textfield
                txtTenDangNhap.requestFocus();
            }
        };
        txtMatKhau.addActionListener(l);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDangNhap().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
