/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package part6LamViecVoiJDBC;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.awt.Window;
import java.net.URL;

/**
 *
 * @author Giang Vu
 */
public class formCuaSoChinh extends javax.swing.JFrame {

    private static int userID = -1;
    private static String tenDangNhap = "";
    
    public static boolean trangThaiDangNhap = false;

    public static int getUserID() {
        return userID;
    }

    public static void setUserID(int userID) {
        formCuaSoChinh.userID = userID;
    }

    public static String getTenDangNhap() {
        return tenDangNhap;
    }

    public static void setTenDangNhap(String tenDangNhap) {
        formCuaSoChinh.tenDangNhap = tenDangNhap;
    }

    /**
     * Creates new form formCuaSoChinh
     */
    public formCuaSoChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHoTen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHeThong = new javax.swing.JMenu();
        jMenuItemNguoiDung = new javax.swing.JMenuItem();
        jMenuItemDanhSachNguoiDung = new javax.swing.JMenuItem();
        jMenuItemThemNguoiDung = new javax.swing.JMenuItem();
        jMenuItemDoiMatKhau = new javax.swing.JMenuItem();
        jMenuItemDangXuat = new javax.swing.JMenuItem();
        jMenuItemDong = new javax.swing.JMenuItem();
        jMenuNghiepVu = new javax.swing.JMenu();
        jMenuItemSinhVien = new javax.swing.JMenuItem();
        jMenuItemChuyenKhoa = new javax.swing.JMenuItem();
        jMenuItemMonHoc = new javax.swing.JMenuItem();
        jMenuItemTraCuu = new javax.swing.JMenuItem();
        jMenuBaoCao = new javax.swing.JMenu();
        jMenuTroGiup = new javax.swing.JMenu();
        jMenuItemWebsite = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cua So Chinh");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblHoTen.setText("none");

        jMenuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/heThong.png"))); // NOI18N
        jMenuHeThong.setText("He thong");

        jMenuItemNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/nguoiDung.png"))); // NOI18N
        jMenuItemNguoiDung.setText("Nguoi dung");
        jMenuItemNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNguoiDungActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemNguoiDung);

        jMenuItemDanhSachNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/danhSachNguoiDung.png"))); // NOI18N
        jMenuItemDanhSachNguoiDung.setText("Danh sach nguoi dung");
        jMenuHeThong.add(jMenuItemDanhSachNguoiDung);

        jMenuItemThemNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/themNguoiDung.png"))); // NOI18N
        jMenuItemThemNguoiDung.setText("Them nguoi dung");
        jMenuItemThemNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThemNguoiDungActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemThemNguoiDung);

        jMenuItemDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/doiMatKhau.png"))); // NOI18N
        jMenuItemDoiMatKhau.setText("Doi mat khau");
        jMenuItemDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDoiMatKhauActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDoiMatKhau);

        jMenuItemDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/dangXuat.png"))); // NOI18N
        jMenuItemDangXuat.setText("Dang xuat");
        jMenuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangXuatActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDangXuat);

        jMenuItemDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/dong.png"))); // NOI18N
        jMenuItemDong.setText("Dong chuong trinh");
        jMenuItemDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDongActionPerformed(evt);
            }
        });
        jMenuHeThong.add(jMenuItemDong);

        jMenuBar1.add(jMenuHeThong);

        jMenuNghiepVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/nghiepVu.png"))); // NOI18N
        jMenuNghiepVu.setText("Nghiep vu");

        jMenuItemSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/sinhVien.png"))); // NOI18N
        jMenuItemSinhVien.setText("Sinh vien");
        jMenuItemSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSinhVienActionPerformed(evt);
            }
        });
        jMenuNghiepVu.add(jMenuItemSinhVien);

        jMenuItemChuyenKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/chuyenKhoa.gif"))); // NOI18N
        jMenuItemChuyenKhoa.setText("Chuyen khoa");
        jMenuNghiepVu.add(jMenuItemChuyenKhoa);

        jMenuItemMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/monHoc.png"))); // NOI18N
        jMenuItemMonHoc.setText("Mon hoc");
        jMenuNghiepVu.add(jMenuItemMonHoc);

        jMenuItemTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/traCuu.gif"))); // NOI18N
        jMenuItemTraCuu.setText("Tra cuu diem thi");
        jMenuNghiepVu.add(jMenuItemTraCuu);

        jMenuBar1.add(jMenuNghiepVu);

        jMenuBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/baoCao.png"))); // NOI18N
        jMenuBaoCao.setText("Bao cao");
        jMenuBar1.add(jMenuBaoCao);

        jMenuTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/troGiup.png"))); // NOI18N
        jMenuTroGiup.setText("Tro giup");

        jMenuItemWebsite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/part6LamViecVoiJDBC/Images/website.png"))); // NOI18N
        jMenuItemWebsite.setText("Website");
        jMenuItemWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWebsiteActionPerformed(evt);
            }
        });
        jMenuTroGiup.add(jMenuItemWebsite);

        jMenuBar1.add(jMenuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(lblHoTen)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHoTen)
                .addGap(0, 265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Mo rong cua so giao dien chinh
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        QuanLyNguoiDung quanLyNguoiDung = new QuanLyNguoiDung();
        NguoiDung objND = quanLyNguoiDung.layThongTinNguoiDung(userID);
        lblHoTen.setText("Xin chao " + objND.getHoTen() + " !");
        if (objND.getQuyen().equals("User")) {
            kiemTraQuyen();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSinhVienActionPerformed
        // TODO add your handling code here:
        formDanhSachSinhVien formDSSV = new formDanhSachSinhVien();
        formDSSV.setVisible(true);
    }//GEN-LAST:event_jMenuItemSinhVienActionPerformed

    private void jMenuItemDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDongActionPerformed
        // TODO add your handling code here:
        int ketQua = JOptionPane.showConfirmDialog(rootPane,
                "Ban co chac chan muon dong chuong trinh khong?",
                "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (ketQua == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemDongActionPerformed

    private void jMenuItemNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNguoiDungActionPerformed
        // TODO add your handling code here:
        formThongTinNguoiDung formTTND = new formThongTinNguoiDung();
        formTTND.setVisible(true);
    }//GEN-LAST:event_jMenuItemNguoiDungActionPerformed
    
    public static void dangXuat() {
        trangThaiDangNhap = false;
        userID = -1;
        tenDangNhap = "";
        // Dong tat ca ca JFrame form dang mo
        Window[] windows = getWindows();
        for (Window window : windows) {
            if (window instanceof JFrame) {
                window.dispose();
            }
        }
        formDangNhap formDN = new formDangNhap();
        formDN.setVisible(true);
    }
    
    private void jMenuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangXuatActionPerformed
        // TODO add your handling code here:
        /*
        trangThaiDangNhap = false;
        userID = -1;
        tenDangNhap = "";
        // Dong tat ca ca JFrame form dang mo
        Window[] windows = getWindows();
        for (Window window : windows) {
            if (window instanceof JFrame) {
                window.dispose();
            }
        }
        formDangNhap formDN = new formDangNhap();
        formDN.setVisible(true);
        */
        dangXuat();
    }//GEN-LAST:event_jMenuItemDangXuatActionPerformed

    private void jMenuItemWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWebsiteActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("https://www.google.com").toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemWebsiteActionPerformed

    private void jMenuItemThemNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThemNguoiDungActionPerformed
        // TODO add your handling code here:
        formThemNguoiDung formTND = new formThemNguoiDung();
        formTND.setVisible(true);
    }//GEN-LAST:event_jMenuItemThemNguoiDungActionPerformed

    private void jMenuItemDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDoiMatKhauActionPerformed
        // TODO add your handling code here:
        formDoiMatKhau formDMK = new formDoiMatKhau();
        formDMK.setVisible(true);
    }//GEN-LAST:event_jMenuItemDoiMatKhauActionPerformed

    /**
     * Ham gioi han quyen khi User dang nhap
     */
    public void kiemTraQuyen() {
        jMenuItemThemNguoiDung.setVisible(!trangThaiDangNhap);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCuaSoChinh.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCuaSoChinh.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCuaSoChinh.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCuaSoChinh.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCuaSoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuBaoCao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHeThong;
    private javax.swing.JMenuItem jMenuItemChuyenKhoa;
    private javax.swing.JMenuItem jMenuItemDangXuat;
    private javax.swing.JMenuItem jMenuItemDanhSachNguoiDung;
    private javax.swing.JMenuItem jMenuItemDoiMatKhau;
    private javax.swing.JMenuItem jMenuItemDong;
    private javax.swing.JMenuItem jMenuItemMonHoc;
    private javax.swing.JMenuItem jMenuItemNguoiDung;
    private javax.swing.JMenuItem jMenuItemSinhVien;
    private javax.swing.JMenuItem jMenuItemThemNguoiDung;
    private javax.swing.JMenuItem jMenuItemTraCuu;
    private javax.swing.JMenuItem jMenuItemWebsite;
    private javax.swing.JMenu jMenuNghiepVu;
    private javax.swing.JMenu jMenuTroGiup;
    private javax.swing.JLabel lblHoTen;
    // End of variables declaration//GEN-END:variables
}
